### PR TITLE
use cki-lib datadefinition

### PR DESCRIPTION
**Pull request by wizardofoz123**
SKT has had issue with its separation of config file and output for a
while. Because it's function is now limited to watching Beaker Jobs,
it's not critical. However, it is a nice example of how the data
definition could be defined and shared.

Signed-off-by: Jakub Racek <jracek@redhat.com>

### CODE REVIEW

**Comment by veruu** [comment]
:+1: for the plan. I didn't look at it too deeply but right now I don't see anything concerning and I like the direction this is going in.

It also looks extensible enough which is awesome - since we want to make skt the only thing interacting with Beaker, we can eventually extend the datastructure to include closer task results. We can already start with the `sum_failed/aborted` and then go even further. I'm getting ahead of myself, I know.

**Comment by wizardofoz123** [comment]
@cki-bot test

**Comment by wizardofoz123** [comment]
@cki-bot test

**Comment by wizardofoz123** [comment]
@cki-bot test

**Comment by veruu** [comment]
Code changes look fine. Let's wait for the bot to verify everything is ok.

**Comment by wizardofoz123** [comment]
As far as I can see, the pipeline failures are testing issues. *holds breath* Merging!

**Pull request merged**
