### PR TITLE
WIP: Make the code python3-compatible

### LINKED ISSUE #338: Make the code python3-compatible
Have skt work with both python2 and python3

### PR DESCRIPTION
**Pull request by danghai**
I make PR to make the code python3-compatible. I set the python3 `env` for catching the error in `python3`. Could you review these commits ?

Fix #338

### CODE REVIEW

**Comment by veruu** [comment]
Yes, using `six` is a good idea.

**Comment by danghai** [comment]
Hi @veruu , I got stuck at this issue: 
```
  File "/home/travis/build/RH-FMK/skt/tests/test_kerneltree.py", line 69, in setUp
    fetch_depth='1'
  File "/home/travis/build/RH-FMK/skt/skt/kerneltree.py", line 60, in __init__
    self.__setup_repository()
  File "/home/travis/build/RH-FMK/skt/skt/kerneltree.py", line 144, in __setup_repository
    if 'origin' in self.__git_cmd("remote").split('\n'):
TypeError: a bytes-like object is required, not 'str'
```
Do you know how to handle it? Thank you

**Comment by veruu** [comment]
@danghai have you tried googling the message and checking the solutions? Another great resource is [the porting guide](https://portingguide.readthedocs.io/en/latest/).

**Comment by danghai** [comment]
@veruu thanks. There are a lot of conflict between `byte` and `string`. In python3 they cannot mix together. I have this issue, I am not sure how to fix it. Do you know how to handle it?
```
Traceback (most recent call last):
  File "/home/travis/build/RH-FMK/skt/tests/test_misc.py", line 72, in test_encoded_patch_subject
    self.assertEqual('[TEST]', skt.misc.get_patch_name(mbox_body))
  File "/home/travis/build/RH-FMK/skt/skt/misc.py", line 78, in get_patch_name
    return ''.join(decoded)
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by veruu** [comment]
Sounds like you aren't converting the `bytes` object to `str`

**Comment by wizardofoz123** [comment]
The code is now Python3 only. Closing.

**Pull request closed without merging**
