### PR TITLE
New config cleanup

### PR DESCRIPTION
**Pull request by wizardofoz123**

### CODE REVIEW

**Comment by wizardofoz123** [comment]
@cki-bot test

**Comment by wizardofoz123** [comment]
@cki-bot test

**Comment by veruu** [comment]
@wizardofoz123 the pipelines seem to be failing with errors like

```
Traceback (most recent call last):
  File "testing-venv/bin/skt", line 10, in <module>
    sys.exit(main())
  File "/builds/cki-project/cki-pipeline/testing-venv/lib/python3.7/site-packages/skt/executable.py", line 254, in main
    retcode = args.func(config_set)
  File "/builds/cki-project/cki-pipeline/testing-venv/lib/python3.7/site-packages/skt/executable.py", line 84, in cmd_run
    save_state(config_set, {'jobid_%s' % (index): job})
  File "/builds/cki-project/cki-pipeline/testing-venv/lib/python3.7/site-packages/skt/executable.py", line 52, in save_state
    temp_parser.read_dict(config_set)
  File "/usr/lib64/python3.7/configparser.py", line 746, in read_dict
    for key, value in keys.items():
AttributeError: 'str' object has no attribute 'items'
2019-07-01 20:12:16,921     INFO   Cancelling pending jobs!
```

Can you please take a look?

**Comment by wizardofoz123** [comment]
@cki-bot test

**Pull request merged**
