### PR TITLE
Add tag to krelease variable (reporter headline)

### PR DESCRIPTION
**Pull request by Toaster192**
Adding more information about the state before the merges to krelease variable.

The tag is also added to the state file now (could be used by itself or to 'restore' the old krelease for whatever reason)

The krelease now looks like this: `3.10.0-1030.el7.skt` instead of `3.10.0.skt`
(tag contains either the 'r' from 'n-v-r' in the RHEL tag or the first 7 characters of the commit hash for upstream)

### CODE REVIEW

**Comment by Toaster192** [comment]
@veruu

**Comment by veruu** [comment]
@cki-bot can you test this please? Up till Beaker submission should be enough so we can check the whiteboard

**Comment by Toaster192** [comment]
Also it's probably arguable what format  hould the krelease with tag be

The krelease is `3.10.0.1030.el7.skt` while the commit msg uses `kernel-3.10.0-1030.el7`

**Comment by veruu** [comment]
@Toaster192 the second one (with the `.skt` added at the end) would be ideal to follow the N-V-R format

**Comment by Toaster192** [comment]
Yeah I agree

**Comment by Toaster192** [comment]
Should now work with every LOCALVERSION (except maybe those that contain '.')

**Comment by veruu** [comment]
@cki-bot can you test the new changes again please? :)

**Comment by Toaster192** [comment]
Also the format looks like this now `3.10.0-1030.el7.foo`

**Comment by Toaster192** [comment]
Um, maybe put the dash symbol into the krelease + tag apendation so the tag in config doesn't start with it?

**Pull request merged**
